# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: swift

script:
- xcodebuild -target GitHubApp -scheme GitHubApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO