# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubApp' do
  use_frameworks!
  
  pod 'RxSwift',   '~> 3.0'
    pod 'RxCocoa',   '~> 3.0'
	pod 'Alamofire', '~> 4.3'
    pod 'SwiftyJSON'
    pod 'SDWebImage', '~> 3.8'

  # Pods for GitHubApp

end
